const quotes = [
    'Believe you can and you\'re halfway there. -Theodore Roosevelt',
    'You have within you right now, everything you need to deal with whatever the world can throw at you. -Brian Tracy',
    'I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination. -Jimmy Dean',
    'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. -Christian D. Larson',
    'Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this. -Chantal Sutherland',
    'I have not failed. I\'ve just found 10,000 ways that won\'t work. -Thomas Edison',
    'You miss 100% of the shots you don\'t take. -Wayne Gretzky',
    'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. -Albert Schweitzer',
    'The only way to do great work is to love what you do. If you haven\'t found it yet, keep looking. Don\'t settle. -Steve Jobs',
    'Success is not final, failure is not fatal: it is the courage to continue that counts. -Winston Churchill',
    'Don\'t watch the clock; do what it does. Keep going. -Sam Levenson',
    'Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this. -Chantal Sutherland',
    'I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination. -Jimmy Dean',
    'It does not matter how slowly you go as long as you do not stop. -Confucius',
    'Strive not to be a success, but rather to be of value. -Albert Einstein',
    'The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. -Winston Churchill',
    'The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela',
    'The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt',
    'If you can dream it, you can achieve it. -Zig Ziglar',
    'The only limit to our realization of tomorrow will be our doubts of today. -Franklin D. Roosevelt',
    'You are never too old to set another goal or to dream a new dream. -C.S. Lewis',
    'The best way to predict the future is to invent it. -Alan Kay',
    'If you want to live a happy life, tie it to a goal, not to people or things. -Albert Einstein',
    'You miss 100% of the shots you don\'t take. -Wayne Gretzky',
    'The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela',
    'I have not failed. I\'ve just found 10,000 ways that won\'t work. -Thomas Edison',
    'It always seems impossible until it\'s done. -Nelson Mandela',
    'Believe you can and you\'re halfway there. -Theodore Roosevelt',
    'Life is 10% what happens to you and 90% how you react to it - Charles R. Swindoll',
    "You are never too old to set another goal or to dream a new dream. -C.S. Lewis",
  "Strive not to be a success, but rather to be of value. -Albert Einstein",
  "I have not failed. I've just found 10,000 ways that won't work. -Thomas Edison",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. -Christian D. Larson",
  "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward. -Martin Luther King Jr.",
  "Happiness is not something ready made. It comes from your own actions. -Dalai Lama",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. -Thomas A. Edison",
  "I would rather die of passion than of boredom. -Vincent van Gogh",
  "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. -Steve Jobs",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. -Winston Churchill",
  "You miss 100% of the shots you don't take. -Wayne Gretzky",
  "The best way to predict your future is to create it. -Abraham Lincoln",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. -Vince Lombardi",
  "Success is not how high you have climbed, but how you make a positive difference to the world. -Roy T. Bennett",
  "The only person you are destined to become is the person you decide to be. -Ralph Waldo Emerson",
  "It does not matter how slowly you go as long as you do not stop. -Confucius",
  "Be the change that you wish to see in the world. -Mahatma Gandhi",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. -Jimmy Dean",
  "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us. -Helen Keller",
  "Life is like riding a bicycle. To keep your balance, you must keep moving. -Albert Einstein",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. -Dr. Seuss",
  "Don't judge each day by the harvest you reap but by the seeds that you plant. -Robert Louis Stevenson",
  "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds. -Orison Swett Marden",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. -Steve Jobs",
  "Believe you can and you're halfway there. -Theodore Roosevelt"
]
  
export function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    return quotes[randomIndex];
  }